name: uniplan
title: UniPlan
base: core24
version: 0.0.1
summary: An all-in-one academic planner for students
description: UniPlan is a comprehensive academic planner built with React Native Expo and Tauri. It is designed to help students manage their academic lives by tracking classes, homework and to-do items
license: Proprietary
website: https://uniplan.dstudios.org
issues: https://github.com/dStudios-735453/UniPlan_Releases/issues
icon: ./favicon.png

grade: stable
confinement: strict

slots:
  uniplan:
    interface: dbus
    bus: session
    name: org.dstudios.uniplan

apps:
  uniplan:
    command: usr/bin/uniplan
    extensions: [gnome]
    plugs:
      - desktop
      - desktop-legacy
      - x11
      - wayland
      - unity7
      - network
    slots:
      - uniplan

platforms:
  amd64:
  arm64:

parts:
  uniplan:
    plugin: dump
    source: package.deb
    override-pull: |
      if [ "$SNAPCRAFT_TARGET_ARCH" = "amd64" ]; then
        curl -L -o package.deb https://github.com/dStudios-735453/UniPlan_Releases/releases/download/v01.05.2026-0806/UniPlan_0.0.1_amd64.deb
      elif [ "$SNAPCRAFT_TARGET_ARCH" = "arm64" ]; then
        curl -L -o package.deb https://github.com/dStudios-735453/UniPlan_Releases/releases/download/v01.05.2026-0806/UniPlan_0.0.1_arm64.deb
      fi
      snapcraftctl pull
    source-type: deb
    stage-packages:
      - libwebkit2gtk-4.1-0
      - libgirepository-1.0-1
