name: uniplan
title: UniPlan
base: core24
version: 0.0.1
summary: An all-in-one academic planner for students
description: UniPlan is a comprehensive academic planner built with React Native Expo and Tauri. It is designed to help students manage their academic lives by tracking classes, homework and to-do items
license: Proprietary
website: https://uniplan.dstudios.org
issues: https://github.com/dStudios-735453/UniPlan_Releases/issues
icon: ./gui/favicon.png

grade: stable
confinement: strict

slots:
  uniplan:
    interface: dbus
    bus: session
    name: org.dstudios.uniplan

apps:
  uniplan:
    command: usr/bin/uniplan
    desktop: ./gui/uniplan.desktop
    extensions: [gnome]
    plugs:
      - desktop
      - desktop-legacy
      - x11
      - wayland
      - unity7
      - network
    slots:
      - uniplan

platforms:
  amd64:
  arm64:

parts:
  uniplan:
    plugin: dump
    source:
      - on amd64: https://github.com/dStudios-735453/UniPlan_Releases/releases/download/v20.05.2026-1728_linux/Uniplan_0.0.1_amd64.deb
      - on arm64: x
    source-type: deb
    stage-packages:
      - libwebkit2gtk-4.1-0
      - libgirepository-1.0-1
  gui-assets:
    plugin: dump
    source: ./gui
    organize:
      "*": ./gui/
