name: Build and Release UniPlan (mobile)

on:
  workflow_dispatch:
    inputs:
      build_android:
        description: "Build Android APK"
        type: boolean
        default: false
      android_build_type:
        description: "Android build profile"
        type: choice
        options:
          - production
          - development
        default: development
      build_ios:
        description: "Build iOS IPA"
        type: boolean
        default: false
      ios_build_type:
        description: "iOS build profile"
        type: choice
        options:
          - production
          - development
        default: development

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.vars.outputs.version }}
      release_title: ${{ steps.vars.outputs.release_title }}
      tag_name: ${{ steps.vars.outputs.tag_name }}
    steps:
      - id: vars
        shell: bash
        run: |
          DATE_TIME=$(date +'%d.%m.%Y-%H%M')

          RELEASE_TITLE="${DATE_TIME}"
          TAG_NAME="v${DATE_TIME}"
          ANDROID_TYPE="${{ github.event.inputs.android_build_type }}"
          IOS_TYPE="${{ github.event.inputs.ios_build_type }}"

          if [ "${{ github.event.inputs.build_android }}" == "true" ]; then
            VERSION="${DATE_TIME}_android:${ANDROID_TYPE}"
          elif [ "${{ github.event.inputs.build_ios }}" == "true" ]; then
            VERSION="${DATE_TIME}_iOS:${IOS_TYPE}"
          else
            VERSION="${DATE_TIME}_mobile_iOS:${IOS_TYPE}_android:${ANDROID_TYPE}"
          fi

          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "release_title=$RELEASE_TITLE" >> $GITHUB_OUTPUT
          echo "tag_name=$TAG_NAME" >> $GITHUB_OUTPUT

  build-mobile:
    needs: prepare
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: android
            os: ubuntu-latest
            build_flag: ${{ github.event.inputs.build_android }}
          - platform: ios
            os: macos-latest
            build_flag: ${{ github.event.inputs.build_ios }}
    runs-on: ${{ matrix.os }}
    env:
      GRADLE_OPTS: -Dorg.gradle.jvmargs="-Xmx4096m -XX:MaxMetaspaceSize=1024m"
    steps:
      - name: Checkout Source
        if: matrix.build_flag == 'true'
        uses: actions/checkout@v6
        with:
          repository: dStudios-735453/UniPlan
          token: ${{ secrets.UNIPLAN_SOURCE_GITHUB }}
          path: source

      - name: Setup Node
        if: matrix.build_flag == 'true'
        uses: actions/setup-node@v6
        with:
          cache: "npm"
          cache-dependency-path: source/package.json

      - name: Install NPM dependencies
        if: matrix.build_flag == 'true'
        working-directory: source
        run: npm install

      - name: Setup Expo and EAS
        if: matrix.build_flag == 'true'
        uses: expo/expo-github-action@v9
        with:
          expo-version: latest
          eas-version: latest
          eas-cache: true
          token: ${{ secrets.EXPO_TOKEN }}
          packager: npm

      - name: Setup Gradle
        if: matrix.platform == 'android' && matrix.build_flag == 'true'
        uses: gradle/actions/setup-gradle@v6

      - name: Build Android
        if: matrix.platform == 'android' && matrix.build_flag == 'true'
        working-directory: source
        shell: bash
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          ANDROID_PROFILE: ${{ github.event.inputs.android_build_type }}
        run: npx eas build --platform android --profile "${ANDROID_PROFILE}" --local --non-interactive

      - name: Prepare xcode
        if: matrix.platform == 'ios' && matrix.build_flag == 'true'
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: Build iOS Production
        if: matrix.platform == 'ios' && matrix.build_flag == 'true' && github.event.inputs.ios_build_type == 'production'
        working-directory: source
        shell: bash
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          IOS_PROFILE: ${{ github.event.inputs.ios_build_type }}
        run: eas build --platform ios --profile production --local --non-interactive --auto-submit

      - name: Build iOS Development
        if: matrix.platform == 'ios' && matrix.build_flag == 'true' && github.event.inputs.ios_build_type == 'development'
        working-directory: source
        shell: bash
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          IOS_PROFILE: ${{ github.event.inputs.ios_build_type }}
        run: eas build --platform ios --profile development --local --non-interactive --output="ios-development.ipa"

      - name: Upload to Diawi
        if: matrix.platform == 'ios' && matrix.build_flag == 'true' && github.event.inputs.ios_build_type == 'development'
        uses: rnkdsh/action-upload-diawi@v1.5.12
        with:
          token: ${{ secrets.DIAWI_TOKEN }}
          file: "source/ios-development.ipa"

      - name: Upload Android Artifact
        if: matrix.platform == 'android' && matrix.build_flag == 'true'
        uses: actions/upload-artifact@v7
        with:
          name: mobile-build-android
          path: |
            source/*.aab
            source/*.apk
            source/android/app/build/outputs/mapping/release/mapping.txt
          retention-days: 2

      - name: Upload iOS Artifact
        if: matrix.platform == 'ios' && matrix.build_flag == 'true'
        uses: actions/upload-artifact@v7
        with:
          name: mobile-build-ios
          path: source/*.ipa
          retention-days: 2

  create-release:
    needs: [prepare, build-mobile]
    runs-on: ubuntu-latest
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v8
        with:
          path: artifacts

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v3
        with:
          tag_name: ${{ needs.prepare.outputs.tag_name }}
          name: ${{ needs.prepare.outputs.release_title }}
          draft: false
          prerelease: true
          files: |
            artifacts/**/*.apk
            artifacts/**/*.aab
            artifacts/**/*.ipa
            artifacts/**/mapping.txt
        env:
          GITHUB_TOKEN: ${{ github.token }}
